#!/usr/bin/python3
import sys
from sys import argv

"""
File_name: factors
Created: 30th of October, 2023
Auth: Mamatiane
Project: RSA-Factoring-Challenge
"""


def factorize(value):

    """
    # Factorize as many numbers as possible into..
    # ..a product of two smaller numbers.
    # VARIABLE(" "):
    # factorize(int) Factorize all the things!
    # Usage: factors <file>
    # Output format: n=p*q
    """
    if value < 2:
        return
    original_value = value
    factors = []

    while value > 1:
        for i in range(2, int(value) + 1):
            if value % i == 0:
                factors.append(i)
                value //= i
                break

    factors_str = "*".join(map(str, factors))
    print(f"{original_value}={factors_str}")

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.strip())
            factorize(value)
            line = file.readline()
except FileNotFoundError:
    print(f'File not found: {argv[1]}')
except ValueError:
    print(f'Invalid input in the file: {argv[1]}')
except Exception as e:
    print(f'An error occurred: {str(e)}')
    pass
