#!/usr/bin/python3
import subprocess
import math
bash_script_path = '/path/to/factors'
input_file_path = '/path/to/your/input/file.txt'

def factorize_number(n):
    factors = []
    while n % 2 == 0:
        factors.append(2)
        n = n // 2
    for i in range(3, int(math.sqrt(n)) + 1, 2):
        while n % i == 0:
            factors.append(i)
            n = n // i
    if n > 2:
        factors.append(n)
    return factors

def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            num = int(line.strip())
            factors = factorize_number(num)
            print(f"{num}={'*'.join(map(str, factors))}")

if __name__ == "__main__":
    import sys
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    filename = sys.argv[1]
    main(filename)
